name: PR to Telegram

on:
  pull_request:
    types: [opened, edited, closed, reopened]

jobs:
  notify_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_ACTION: ${{ github.event.action }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: |
          MESSAGE="Pull Request *${PR_ACTION}* por ${PR_USER}:\n*${PR_TITLE}*\n${PR_URL}"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
